package com.mkdh.vendorbridge.Utils;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.Map;

@Component
public class PdfDocumentGenerator {

    private static final Font TITLE_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
    private static final Font HEADER_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
    private static final Font BODY_FONT = FontFactory.getFont(FontFactory.HELVETICA, 11);

    public byte[] generatePurchaseOrderPdf(String poNumber, String vendorName, String vendorEmail,
                                           String vendorGst, String vendorAddress, String rfqTitle,
                                           String itemDescription, Integer quantity, BigDecimal unitPrice,
                                           BigDecimal totalAmount, String status, String createdBy,
                                           LocalDateTime createdAt) {
        Map<String, String> fields = new LinkedHashMap<>();
        fields.put("PO Number", poNumber);
        fields.put("RFQ", rfqTitle);
        fields.put("Vendor", vendorName);
        fields.put("Email", vendorEmail);
        fields.put("GST Number", vendorGst);
        fields.put("Address", vendorAddress);
        fields.put("Item", itemDescription);
        fields.put("Quantity", String.valueOf(quantity));
        fields.put("Unit Price", formatCurrency(unitPrice));
        fields.put("Total Amount", formatCurrency(totalAmount));
        fields.put("Status", status);
        fields.put("Created By", createdBy);
        fields.put("Created At", formatDateTime(createdAt));
        return buildDocument("Purchase Order", fields);
    }

    public byte[] generateInvoicePdf(String invoiceNumber, String poNumber, String vendorName,
                                     String vendorEmail, String vendorGst, String itemDescription,
                                     Integer quantity, BigDecimal unitPrice, BigDecimal subtotal,
                                     BigDecimal gstRate, BigDecimal gstAmount, BigDecimal grandTotal,
                                     String generatedBy, LocalDateTime createdAt) {
        Map<String, String> fields = new LinkedHashMap<>();
        fields.put("Invoice Number", invoiceNumber);
        fields.put("PO Number", poNumber);
        fields.put("Vendor", vendorName);
        fields.put("Email", vendorEmail);
        fields.put("GST Number", vendorGst);
        fields.put("Item", itemDescription);
        fields.put("Quantity", String.valueOf(quantity));
        fields.put("Unit Price", formatCurrency(unitPrice));
        fields.put("Subtotal", formatCurrency(subtotal));
        fields.put("GST Rate", gstRate + "%");
        fields.put("GST Amount", formatCurrency(gstAmount));
        fields.put("Grand Total", formatCurrency(grandTotal));
        fields.put("Generated By", generatedBy);
        fields.put("Created At", formatDateTime(createdAt));
        return buildDocument("Tax Invoice", fields);
    }

    private byte[] buildDocument(String title, Map<String, String> fields) {
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4, 36, 36, 36, 36);
            PdfWriter.getInstance(document, outputStream);
            document.open();

            Paragraph titleParagraph = new Paragraph(title, TITLE_FONT);
            titleParagraph.setAlignment(Element.ALIGN_CENTER);
            titleParagraph.setSpacingAfter(20);
            document.add(titleParagraph);

            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{35f, 65f});

            for (Map.Entry<String, String> entry : fields.entrySet()) {
                table.addCell(labelCell(entry.getKey()));
                table.addCell(valueCell(entry.getValue()));
            }

            document.add(table);
            document.close();
            return outputStream.toByteArray();
        } catch (Exception e) {
            throw new IllegalStateException("Failed to generate PDF", e);
        }
    }

    private PdfPCell labelCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, HEADER_FONT));
        cell.setPadding(8);
        cell.setBackgroundColor(new java.awt.Color(240, 240, 240));
        return cell;
    }

    private PdfPCell valueCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text != null ? text : "-", BODY_FONT));
        cell.setPadding(8);
        return cell;
    }

    private String formatCurrency(BigDecimal amount) {
        return amount != null ? "INR " + amount : "-";
    }

    private String formatDateTime(LocalDateTime dateTime) {
        return dateTime != null
                ? dateTime.format(DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm"))
                : "-";
    }
}
